/* Deterministic simulation core: renderer-independent, elapsed-time based. */
(()=>{'use strict';
const TYPES={resonator:{name:'Резонатор',icon:'✧',cost:[70,8],desc:'Энергия и резонанс'},extractor:{name:'Экстрактор',icon:'◈',cost:[55,12],desc:'Дрон добывает жилу'},radiator:{name:'Холодильная лопасть',icon:'❋',cost:[35,15],desc:'Охлаждение узлов вокруг'},relay:{name:'Жиловой тракт',icon:'◇',cost:[20,2],desc:'Расширяет живую сеть'},nest:{name:'Гнездо отростков',icon:'⌘',cost:[85,14],desc:'Дроны и дальняя логистика'},lab:{name:'Узел памяти',icon:'⌬',cost:[95,16],desc:'Исследование · осколки'},battery:{name:'Эхо-накопитель',icon:'▣',cost:[75,10],desc:'Запас до 180 энергии'},refinery:{name:'Кристаллообогатитель',icon:'⛭',cost:[55,9],desc:'Плавит руду в реальные кристаллические слитки'},crystallizer:{name:'Кристаллизатор',icon:'❖',cost:[130,22],desc:'Синтезирует Ксенокварц'},ward:{name:'Гармонический щит',icon:'⛨',cost:[90,18],desc:'Защищает от метеоритов'},chamber:{name:'Камера Слияния',icon:'◉',cost:[180,35],desc:'Ритуал Тела II'}};
const TECHS=[
{id:'morph',name:'Кристаллическая морфология',branch:'Морфология',cost:4,energy:25,desc:'Рост быстрее на 40%; строительство дешевле на 10%.'},
{id:'veins',name:'Слух жил',branch:'Морфология',cost:5,energy:40,req:'morph',desc:'Добыча +60%; жилы отображаются яснее.'},
{id:'thermal',name:'Терморегуляция',branch:'Терморегуляция',cost:5,energy:40,desc:'Радиаторы охлаждают вдвое сильнее; тепло растёт медленнее.'},
{id:'harmonics',name:'Гармоники пустоты',branch:'Резонанс',cost:7,energy:55,desc:'Открывает 1200 Гц и аккорд 432/1200 для синтеза.'},
{id:'accord',name:'Двойной аккорд',branch:'Резонанс',cost:8,energy:70,req:'harmonics',desc:'Резонансная устойчивость +25%; снижает диссонанс ритуала.'},
{id:'autonomy',name:'Автономные отростки',branch:'Логистика',cost:5,energy:35,desc:'Гнездо добавляет второго грузового носителя для сети.'},
{id:'swarm',name:'Рой-сборщик',branch:'Логистика',cost:7,energy:55,req:'autonomy',desc:'Дальность сети +25%; носители движутся быстрее.'},
{id:'memory',name:'Память Матки',branch:'Память',cost:8,energy:60,desc:'Открывает Кристаллизатор и Камеру Слияния.'},
{id:'xeno',name:'Синтез Ксенокварца',branch:'Память',cost:10,energy:90,req:'memory',desc:'Разблокирует образование редкого ядра Ксенокварца.'}
];
const DEPOSITS=[{x:-205,y:-115,r:43,type:'silicate',qty:1600},{x:220,y:-190,r:48,type:'silicate',qty:1800},{x:265,y:180,r:43,type:'silicate',qty:1600},{x:-220,y:190,r:39,type:'silicate',qty:1600},{x:30,y:-270,r:37,type:'metal',qty:650},{x:5,y:265,r:42,type:'metal',qty:720},{x:335,y:8,r:34,type:'shard',qty:240},{x:-340,y:4,r:33,type:'shard',qty:240},{x:0,y:0,r:0,type:'core',qty:0}];
const CORE={x:0,y:0},LINK=155;
function fresh(){return {version:3,t:0,resources:{sil:300,metal:90,energy:0,shards:0,xeno:0},deposits:DEPOSITS.map(d=>({...d})),nodes:[],drones:[],items:[],tech:[],freq:432,mode:'base',paused:false,speed:1,selected:null,ritual:null,ritualProgress:0,won:false,storm:0,stormNext:270,stormDone:0,log:['Матка пробуждена. Фоновый сигнал позволяет вырастить первый резонатор.'],stats:{delivered:0,researched:0},nextId:1,nextItemId:1}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function has(s,id){return s.tech.includes(id)}function tech(id){return TECHS.find(t=>t.id===id)}function networkRange(s){return LINK*(has(s,'swarm')?1.25:1)}
function connected(s,target){let range=networkRange(s),seen=new Set(),q=[{...CORE,id:0}];while(q.length){let a=q.shift();if(dist(a,target)<=range)return true;for(let n of s.nodes){if(n.id===target.id||seen.has(n.id)||n.grow>0||n.type==='radiator')continue;if(dist(a,n)<=range){seen.add(n.id);q.push(n)}}}return false}
function nearDeposit(s,p,type){return s.deposits.some(d=>d.type===type&&d.qty>0&&dist(p,d)<d.r+25)}
function allowed(s,type){if(type==='chamber'&&!has(s,'memory'))return false;if(type==='crystallizer'&&!has(s,'xeno'))return false;if(type==='nest'&&!has(s,'autonomy'))return false;return true}
function canPlace(s,type,p){let def=TYPES[type];if(!def)return {ok:false,why:'Неизвестная форма'};if(!allowed(s,type))return {ok:false,why:'Нужна соответствующая технология'};if(Math.abs(p.x)>390||Math.abs(p.y)>310)return {ok:false,why:'За границей устойчивой поверхности'};if(dist(p,CORE)<48||s.nodes.some(n=>dist(p,n)<39))return {ok:false,why:'Место занято — отступи от узла'};if(type==='extractor'&&!['silicate','metal','shard'].some(k=>nearDeposit(s,p,k)))return {ok:false,why:'Нет месторождения поблизости'};if(type!=='extractor'&&s.deposits.some(d=>d.type!=='core'&&dist(p,d)<d.r+8))return {ok:false,why:'Не ставь на саму жилу'};if(type!=='resonator'&&!connected(s,{...p,id:-1}))return {ok:false,why:'Не подключено: построй ближе или протяни тракт'};let [a,m]=def.cost,discount=has(s,'morph')?.9:1;if(s.resources.sil<a*discount||s.resources.metal<m)return {ok:false,why:'Недостаточно ресурсов'};return {ok:true,why:type==='extractor'?'Жила найдена; сеть подключится':'Место подходит'}}
function addLog(s,text){s.log.unshift(text);s.log=s.log.slice(0,70);window.SilLog?.push('info','model.event',{text,gameTime:+s.t.toFixed(2)})}
function build(s,type,p){let check=canPlace(s,type,p);if(!check.ok)return check;let [a,m]=TYPES[type].cost,disc=has(s,'morph')?.9:1;s.resources.sil-=Math.ceil(a*disc);s.resources.metal-=m;let n={id:s.nextId++,type,x:p.x,y:p.y,grow:has(s,'morph')?1.5:2.5,heat:10,age:0,work:0,charge:0,active:true,level:0,mode:type==='resonator'?(s.mode||'base'):'base'};s.nodes.push(n);addLog(s,`${TYPES[type].name}: корень вплетён в жиловую сеть.`);return {ok:true,node:n}}
function research(s,id){let t=tech(id);if(!t||has(s,id))return {ok:false,why:'Уже изучено или неизвестно'};if(t.req&&!has(s,t.req))return {ok:false,why:`Нужна технология «${tech(t.req).name}»`};if(!s.nodes.some(n=>n.type==='lab'&&n.grow<=0&&connected(s,n)))return {ok:false,why:'Нет подключённого Узла памяти'};if(s.resources.shards<t.cost||s.resources.energy<t.energy)return {ok:false,why:'Недостаточно осколков или энергии'};s.resources.shards-=t.cost;s.resources.energy-=t.energy;s.tech.push(id);s.stats.researched++;addLog(s,`Память Матки раскрылась: ${t.name}. ${t.desc}`);return {ok:true}}
function getPhase(s){if(s.won)return ['ТЕЛО II · ПРОБУЖДЕНО','Глава I завершена. Следующая глава ещё не открыта.'];if(!s.nodes.some(n=>n.type==='resonator'&&n.grow<=0))return ['ПРОБУЖДЕНИЕ','Матка шлёт фоновый сигнал. Вырасти первый резонатор — начальная энергия не нужна.'];if(!s.nodes.some(n=>n.type==='extractor'&&n.grow<=0))return ['ПЕРВЫЕ ЖИЛЫ','Подключи экстрактор к месторождению. Дрон доставит груз в Матку.'];if(!s.nodes.some(n=>n.type==='radiator'&&n.grow<=0))return ['ТЕПЛОВОЕ РАВНОВЕСИЕ','Узел нагревается. Радиатор рядом охлаждает локально; расширяй сеть трактами.'];if(!has(s,'harmonics'))return ['ПАМЯТЬ И РЕЗОНАНС','Построй Узел памяти, изучи Гармоники пустоты и открой второй режим.'];if(!has(s,'xeno'))return ['ОТЗВУКИ КСЕНОКВАРЦА','Собери аккорд: базовый резонатор 432 Гц, дальний — 1200 Гц. Открой синтез Ксенокварца.'];if(s.resources.xeno<1)return ['РЕДКОЕ СЕРДЦЕ','Построй Кристаллизатор у подключённого Узла памяти. Аккорд 432 + 1200 создаёт Ксенокварц.'];if(!s.nodes.some(n=>n.type==='chamber'&&n.grow<=0))return ['КАМЕРА СЛИЯНИЯ','Построй камеру на подготовленной площадке и защити её от метеоритного дождя.'];if(!s.ritual)return ['ПОДГОТОВКА К СЛИЯНИЮ','Запусти ритуал у камеры. Нужен запас ≥100 энергии и сеть в аккорде 432/1200 Гц.'];return ['СЛИЯНИЕ','Удерживай аккорд 1200 Гц: энергия расходуется, диссонанс и метеоры сбивают ритуал.']}
function startRitual(s){if(!s.nodes.some(n=>n.type==='chamber'&&n.grow<=0))return {ok:false,why:'Камера Слияния не построена'};if(s.resources.xeno<1)return {ok:false,why:'Нет Ксенокварца'};if(s.resources.energy<100)return {ok:false,why:'Нужно 100 энергии для запуска'};s.resources.xeno--;s.resources.energy-=100;s.ritual={active:true,elapsed:0,stress:0};s.ritualProgress=0;addLog(s,'Ритуал начался. Стабилизируй сеть на 1200 Гц и береги энергию.');return {ok:true}}
function makeCargo(s,kind,amount,x,y,phase,source){const item={id:s.nextItemId++,kind,amount,x,y,phase,source,carrier:null,facility:null,work:0};s.items ||= [];s.items.push(item);addLog(s,`Груз создан: ${kind} ×${amount} у добывающего узла ${source}.`);return item}
function facilityFor(s,item){let wanted=item.kind==='shard'?'lab':'refinery';return s.nodes.find(n=>n.type===wanted&&n.grow<=0&&connected(s,n))||null}
function tick(s,dt){if(s.paused||s.won)return {frozen:true,gameTime:s.t};dt=Math.min(dt,.2)*s.speed;if(!Number.isFinite(dt)||dt<=0)return {frozen:false,gameTime:s.t};s.t+=dt;let R=s.resources;s.items ||= [];s.nextItemId ||= 1;let range=networkRange(s),connectedNodes=s.nodes.filter(n=>n.grow<=0&&connected(s,n)),resonators=connectedNodes.filter(n=>n.type==='resonator'),radiators=connectedNodes.filter(n=>n.type==='radiator'),extractors=connectedNodes.filter(n=>n.type==='extractor'),labs=connectedNodes.filter(n=>n.type==='lab'),refineries=connectedNodes.filter(n=>n.type==='refinery');let freqOK=n=>Math.abs(s.freq-(n.mode==='high'?1200:432))<=(has(s,'accord')?9:5),pIn=0,pOut=0;
// Generation, heat and mining create PHYSICAL unrefined cargo, never finished inventory.
for(let n of s.nodes){if(n.grow>0){n.grow=Math.max(0,n.grow-dt*(has(s,'morph')?1.4:1));continue}n.age+=dt;let cooled=radiators.some(r=>dist(n,r)<165),cool=cooled?(has(s,'thermal')?4:2):0,quality=freqOK(n)?1:Math.max(.12,1-Math.abs(s.freq-(n.mode==='high'?1200:432))/260),heat=0;
if(n.type==='resonator'&&connected(s,n)){pIn+=2.5*quality*(n.heat>90?.25:1);heat=.8+(1-quality)*2.4}
if(n.type==='extractor'&&connected(s,n)){let d=s.deposits.find(q=>q.qty>0&&dist(n,q)<q.r+25);if(d&&n.heat<100){heat=1.1;if(s.items.filter(i=>i.source===n.id).length<2)n.work+=dt;else n.work=Math.min(n.work,12);if(n.work>=12&&s.items.length<180&&s.items.filter(i=>i.source===n.id).length<2){n.work-=12;let amount=(d.type==='shard'?3:5)*(has(s,'veins')?1.6:1);makeCargo(s,d.type,amount,n.x,n.y,'ground',n.id);d.qty=Math.max(0,d.qty-amount)}}}
if(n.type==='lab'&&connected(s,n)){heat=.35;pOut+=.18}
if(n.type==='refinery'&&connected(s,n)){heat=.55;pOut+=.22}
if(n.type==='crystallizer'&&connected(s,n)){heat=1.2;pOut+=.3}
if(n.type==='ward'&&connected(s,n))heat=.45;if(n.type==='battery'&&connected(s,n))n.charge=Math.min(180,n.charge+Math.max(0,pIn-pOut)*dt);if(n.type==='chamber'&&connected(s,n)&&s.ritual)heat=2;
n.heat=Math.max(7,Math.min(125,n.heat+(heat-cool-(n.type==='radiator'?.15:0))*(has(s,'thermal')?.65:1)*dt));}
for(let n of extractors)if(s.deposits.some(d=>d.qty>0&&dist(n,d)<d.r+25))pOut+=.35;let net=pIn-pOut;R.energy=Math.max(0,Math.min(999,R.energy+net*dt));
// Factory transformation: delivered raw cargo sits in a real input queue for processing time.
for(let facility of [...refineries,...labs]){if(facility.heat>=100)continue;let allowedKind=facility.type==='lab'?'shard':['silicate','metal'];let item=s.items.find(i=>i.phase==='atFactory'&&i.facility===facility.id&&allowedKind.includes(i.kind));if(!item)continue;item.work+=dt;if(item.work>=2.8){let output=item.kind==='shard'?'shards':item.kind;item.kind=output;item.phase='product';item.facility=null;item.work=0;facility.work=0;addLog(s,`${TYPES[facility.type].name} переработал сырьё → ${output} ×${item.amount}.`)}else facility.work=item.work}
// Crystallizer input/output also obeys a material-processing delay and uses stored resonance shards.
let crystallizer=s.nodes.find(n=>n.type==='crystallizer'&&n.grow<=0&&connected(s,n));if(crystallizer){crystallizer.work+=dt;let base=resonators.some(n=>n.mode==='base'),high=resonators.some(n=>n.mode==='high');if(base&&high&&Math.abs(s.freq-432)<=8&&has(s,'xeno')&&R.shards>=1&&crystallizer.work>=24){crystallizer.work-=24;R.shards--;makeCargo(s,'xeno',1,crystallizer.x,crystallizer.y,'product',crystallizer.id);addLog(s,'Кристаллизатор создал материальный объект Ксенокварца.')}}
// Physical couriers. Mining drone is a seed organism; autonomy + nests add capacity, never direct resources.
let nests=connectedNodes.filter(n=>n.type==='nest');let desired=extractors.length?extractors.length+nests.length*(has(s,'swarm')?2:1):0;desired=Math.min(desired,Math.max(1,extractors.length*(has(s,'swarm')?3:2)));for(let i=s.drones.length;i<desired;i++){let home=extractors[i%extractors.length];if(!home)break;s.drones.push({id:i+1,node:home.id,x:home.x,y:home.y,phase:'idle',cargo:null,speed:has(s,'swarm')?78:55})}
for(let drone of s.drones){let home=s.nodes.find(n=>n.id===drone.node)||extractors[0];if(!home)continue;if(drone.phase==='idle'){let item=s.items.find(i=>i.phase==='ground'&&facilityFor(s,i));if(item){let dest=facilityFor(s,item);drone.cargo=item.id;drone.target=dest.id;drone.phase='toOre';item.carrier=drone.id;item.phase='picked';addLog(s,`Носитель ${drone.id} поднял груз ${item.kind} ×${item.amount}.`)}}
let item=s.items.find(i=>i.id===drone.cargo);let target=null;if(drone.phase==='toOre')target=item?item:null;else if(drone.phase==='toFactory')target=s.nodes.find(n=>n.id===drone.target);else if(drone.phase==='toCore')target={x:CORE.x,y:CORE.y};else if(drone.phase==='return')target=home;
if(target){let dx=target.x-drone.x,dy=target.y-drone.y,distance=Math.hypot(dx,dy),step=drone.speed*dt;if(distance<=step||distance<.01){drone.x=target.x;drone.y=target.y;if(drone.phase==='toOre'&&item){drone.phase='toFactory';item.phase='carried';}else if(drone.phase==='toFactory'&&item){item.phase='atFactory';item.facility=drone.target;item.carrier=null;drone.cargo=null;drone.phase='return';addLog(s,`Сырьё доставлено на фабрику ${TYPES[s.nodes.find(n=>n.id===drone.target)?.type]?.name||'переработки'}.`)}else if(drone.phase==='toCore'&&item){if(item.kind==='silicate')R.sil+=item.amount;else if(item.kind==='metal')R.metal+=item.amount;else if(item.kind==='shards')R.shards+=item.amount;else if(item.kind==='xeno')R.xeno+=item.amount;s.stats.delivered+=item.amount;s.items=s.items.filter(q=>q.id!==item.id);drone.cargo=null;drone.phase='return';addLog(s,`Матка приняла готовый груз ${item.kind} ×${item.amount}.`)}else if(drone.phase==='return')drone.phase='idle'}else{drone.x+=dx/distance*step;drone.y+=dy/distance*step;if(item&&(drone.phase==='toOre'||drone.phase==='toFactory')){item.x=drone.x;item.y=drone.y}}}
// Finished factory products are discrete entities too; carrier brings them from plant to Matriarch.
if(drone.phase==='idle'){let product=s.items.find(i=>i.phase==='product');if(product){drone.cargo=product.id;drone.phase='toCore';product.phase='carriedProduct';product.carrier=drone.id;addLog(s,`Носитель ${drone.id} принял готовый продукт ${product.kind} для Матки.`)}}}
// A delivered product becomes usable inventory only at Matriarch intake.
for(let i of s.items)if(i.phase==='product'&&i.carrier==null){/* idle drones acquire it on the next simulation step */}
if(s.t>=s.stormNext&&!s.storm){s.storm=24;s.stormDone++;s.stormNext=s.t+360;addLog(s,'МЕТЕОРИТНЫЙ ФРОНТ: укрой узлы у Гармонического щита.')}
if(s.storm>0){s.storm=Math.max(0,s.storm-dt);if(Math.floor(s.storm*2)%7===0&&Math.random()<dt*.16){let vulnerable=s.nodes.filter(n=>n.grow<=0&&n.type!=='ward'&&!connectedNodes.some(w=>w.type==='ward'&&dist(n,w)<150));if(vulnerable.length){let n=vulnerable[Math.floor(Math.random()*vulnerable.length)];n.heat=Math.min(125,n.heat+18);addLog(s,`Метеоритный жар ударил по узлу (${TYPES[n.type].name}).`)}}}
let hot=s.nodes.some(n=>n.heat>=100),frequencyGood=Math.abs(s.freq-1200)<=8,networkGood=resonators.some(n=>n.mode==='high')&&resonators.some(n=>n.mode==='base')&&frequencyGood;if(s.ritual){let stress=(hot?1.4:0)+(networkGood?0:.9)+(s.storm?1:0)+(net<.1?1.3:0)-(has(s,'accord')?.5:0);s.ritual.stress=Math.max(0,s.ritual.stress+stress*dt-.35*dt);if(networkGood&&!hot&&net>.1&&R.energy>0){s.ritual.elapsed+=dt;R.energy=Math.max(0,R.energy-1.8*dt);s.ritualProgress=s.ritual.elapsed/45}else{s.ritual.elapsed=Math.max(0,s.ritual.elapsed-dt*(.25+s.ritual.stress*.03));s.ritualProgress=s.ritual.elapsed/45}if(s.ritual.stress>24){s.ritual=null;s.ritualProgress=0;addLog(s,'Ритуал сорвался от диссонанса. Ксенокварц сохранён; восстанови энергию и попробуй снова.');R.xeno++}else if(s.ritual.elapsed>=45){s.won=true;s.ritual=null;s.ritualProgress=1;addLog(s,'Слияние завершено. Тело II пробудилось. За границей астероида — новый зов.')}}
return {pIn,pOut,net,hot,connectedNodes,resonators,radiators,extractors,labs,refineries,range,items:s.items.length,drones:s.drones.length,simSeconds:dt}}
function serialize(s){return JSON.stringify({version:3,state:s})}function deserialize(raw){try{let o=JSON.parse(raw);if(![2,3].includes(o.version)||!o.state||!Array.isArray(o.state.nodes))return null;let base=fresh(),restored=Object.assign(base,o.state,{paused:false,speed:[1,2,3].includes(o.state.speed)?o.state.speed:1,resources:Object.assign(base.resources,o.state.resources||{}),stats:Object.assign(base.stats,o.state.stats||{}),deposits:Array.isArray(o.state.deposits)?o.state.deposits:base.deposits,items:Array.isArray(o.state.items)?o.state.items:[],drones:o.version===2?[]:(Array.isArray(o.state.drones)?o.state.drones:[])});restored.nextId=Math.max(1,restored.nextId||1);restored.nextItemId=Math.max(1,restored.nextItemId||1);return restored}catch{return null}}
window.SilModel={TYPES,TECHS,DEPOSITS,CORE,LINK,fresh,dist,has,connected,nearDeposit,canPlace,build,research,getPhase,startRitual,tick,serialize,deserialize,addLog};})();