import * as THREE from './vendor/three.module.js';
(()=>{'use strict';const canvas=document.querySelector('#world');let renderer,scene,camera,asteroid,coreGroup,networkGroup,depositGroup,buildingGroup,droneGroup,cargoGroup,routeLine,particleField,raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),W=1,H=1,buildMeshes=new Map(),droneMeshes=new Map(),cargoMeshes=new Map(),signature='',effects=true,lastView={},networkKey='',overlayKey='';const V=(x,y,z)=>new THREE.Vector3(x,y,z);const mat=(color,emissive=color,emissiveIntensity=.18,roughness=.38,metalness=.15)=>new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity,roughness,metalness});
const materials={rock:mat('#536064','#17242a',.12,.91),rock2:mat('#36434a','#10171c',.05,.95),teal:mat('#72e9df','#3ef5e1',1.15,.24,.25),cyan:mat('#69d6e9','#27cceb',.9,.24,.25),gold:mat('#ebbd71','#f5a43d',.8,.3,.3),violet:mat('#b081e7','#954bed',1,.23,.3),ice:mat('#a6c6ff','#82aaff',.9,.25,.2),red:mat('#ff735f','#fb432d',1.2,.25,.2),white:mat('#d6fff6','#8ffff0',1.4,.2,.1),dark:mat('#111923','#101923',.06,.82)};
function heightAt(x,z){let q=Math.max(.03,1-(x*x/(366*366))-(z*z/(300*300)));let ridge=5*Math.sin(x*.027)*Math.cos(z*.033)+2.8*Math.sin(z*.061+x*.035);return 50*Math.sqrt(q)+ridge}
function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.setClearColor('#07101a');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.16;renderer.shadowMap.enabled=false;scene=new THREE.Scene();scene.background=new THREE.Color('#07101a');scene.fog=new THREE.FogExp2('#07101a',.00072);camera=new THREE.PerspectiveCamera(43,1,.1,2500);scene.add(new THREE.HemisphereLight('#bbd9ed','#171d2b',2.1));let key=new THREE.DirectionalLight('#e5f5ff',3.1);key.position.set(-210,420,180);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);let rim=new THREE.DirectionalLight('#5a75e8',2.4);rim.position.set(250,100,-260);scene.add(rim);let fill=new THREE.PointLight('#3fe8df',72,440,2);fill.position.set(0,88,0);scene.add(fill);scene.add(new THREE.AmbientLight('#7892a8',.58));
const geo=new THREE.IcosahedronGeometry(1,5),pos=geo.attributes.position,colors=[];for(let i=0;i<pos.count;i++){let x=pos.getX(i),y=pos.getY(i),z=pos.getZ(i),noise=1+.04*Math.sin(x*19+z*17)*Math.cos(y*20)+.026*Math.sin(z*39+y*13)+.012*Math.cos(x*47-y*8);pos.setXYZ(i,x*360*noise,y*54*noise,z*295*noise);let shade=.79+.12*Math.sin(x*8+z*11)*Math.cos(y*15)+.07*Math.sin(z*25+y*9);colors.push(.48*shade,.56*shade,.56*shade)}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();asteroid=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#a6b0a9',vertexColors:true,roughness:.95,metalness:.02,flatShading:true}));asteroid.receiveShadow=true;scene.add(asteroid);const under=new THREE.Mesh(new THREE.IcosahedronGeometry(1,4),mat('#17242d','#09121d',.05,.96));under.scale.set(362,48,298);under.position.y=-18;scene.add(under);for(let i=0;i<65;i++){let a=i*2.399,rr=68+(i*53)%258,x=Math.cos(a)*rr,z=Math.sin(a)*rr*.79;if(x*x/(350*350)+z*z/(280*280)>.88)continue;let skip=window.SilModel?.DEPOSITS?.some(d=>d.type!=='core'&&Math.hypot(x-d.x,z-d.y)<d.r+32);if(skip)continue;let rock=new THREE.Mesh(new THREE.DodecahedronGeometry(2.5+(i%5)*1.4,0),i%4===0?materials.ice:materials.rock2);rock.position.set(x,heightAt(x,z)+1.7,z);rock.scale.y=.28+(i%4)*.12;rock.rotation.set(i*.7,i*1.2,i*.3);scene.add(rock)}
networkGroup=new THREE.Group();depositGroup=new THREE.Group();buildingGroup=new THREE.Group();droneGroup=new THREE.Group();cargoGroup=new THREE.Group();scene.add(networkGroup,depositGroup,buildingGroup,droneGroup,cargoGroup);let routeGeo=new THREE.BufferGeometry();routeGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(6*16),3));routeGeo.setDrawRange(0,0);routeLine=new THREE.LineSegments(routeGeo,new THREE.LineBasicMaterial({color:'#77f4d5',transparent:true,opacity:.32}));scene.add(routeLine);
// starfield, real 3D points
let starPos=[];for(let i=0;i<800;i++){let a=Math.random()*Math.PI*2,r=580+Math.random()*850;starPos.push(Math.cos(a)*r,Math.random()*1000-300,Math.sin(a)*r)}let sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(starPos,3));particleField=new THREE.Points(sg,new THREE.PointsMaterial({color:'#9cb9d7',size:1.5,transparent:true,opacity:.68,sizeAttenuation:true}));scene.add(particleField);
// central Matriarch: sculpted growing crystal crown
coreGroup=new THREE.Group();let plinth=new THREE.Mesh(new THREE.CylinderGeometry(23,31,8,9),mat('#30474b','#216965',.8,.32));plinth.position.y=heightAt(0,0)+3;plinth.castShadow=true;coreGroup.add(plinth);for(let i=0;i<7;i++){let a=i*Math.PI*2/7,r=15+Math.sin(i*4)*3,mesh=new THREE.Mesh(new CrystalGeometry(10,46+(i%3)*8),materials.teal);mesh.position.set(Math.cos(a)*r,heightAt(0,0)+22,Math.sin(a)*r);mesh.rotation.z=(i%2?-.12:.1);mesh.rotation.y=a;mesh.castShadow=true;coreGroup.add(mesh)}let heart=new THREE.Mesh(new THREE.OctahedronGeometry(8,1),materials.white);heart.position.y=heightAt(0,0)+46;coreGroup.add(heart);scene.add(coreGroup);
resize();window.addEventListener('resize',resize)}catch(e){window.SilLog?.push('error','webgl.init.failed',{message:e.message,stack:e.stack});canvas.dataset.error='WebGL не удалось запустить. Обнови драйвер браузера или включи аппаратное ускорение.';}}
function resize(){if(!renderer)return;let r=canvas.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);renderer.setSize(W,H,false);camera.aspect=W/H;camera.updateProjectionMatrix()}
function colorFor(type,heat=0){if(heat>=90)return materials.red;return ({resonator:materials.teal,extractor:materials.gold,radiator:materials.ice,relay:materials.cyan,nest:materials.violet,lab:materials.ice,battery:materials.cyan,refinery:materials.gold,crystallizer:materials.violet,ward:materials.ice,chamber:materials.violet})[type]||materials.teal}
function positionOf(p,h=0){return V(p.x,heightAt(p.x,p.y)+h,p.y)}function geometryFor(type){switch(type){case'resonator':return new CrystalGeometry(9,28);case'extractor':return new CrystalGeometry(11,19);case'radiator':return new THREE.CylinderGeometry(11,14,8,8);case'relay':return new CrystalGeometry(7,17);case'nest':return new THREE.CylinderGeometry(12,17,18,7);case'lab':return new CrystalGeometry(12,26);case'battery':return new THREE.CylinderGeometry(10,13,19,8);case'refinery':return new THREE.CylinderGeometry(13,17,20,7);case'crystallizer':return new CrystalGeometry(15,30);case'ward':return new THREE.CylinderGeometry(13,18,25,6);case'chamber':return new THREE.TorusGeometry(18,4,8,20);default:return new CrystalGeometry(10,20)}}
function makeBuilding(n){let g=new THREE.Group(),base=new THREE.Mesh(new THREE.CylinderGeometry(10,14,5,8),mat('#25363a','#1b4c4d',.5,.55));base.position.y=3;base.castShadow=true;g.add(base);let m=new THREE.Mesh(geometryFor(n.type),colorFor(n.type,n.heat));m.position.y=n.type==='chamber'?13:12;m.castShadow=true;m.receiveShadow=true;g.add(m);if(n.type==='radiator'){for(let k=0;k<4;k++){let f=new THREE.Mesh(new THREE.BoxGeometry(2,2,17),materials.ice);f.position.set((k-1.5)*5,6,0);f.rotation.y=Math.PI/2;g.add(f)}}if(n.type==='chamber'){m.rotation.x=Math.PI/2;m.position.y=13}if(n.type==='extractor'){let drill=new THREE.Mesh(new THREE.ConeGeometry(3,13,6),materials.gold);drill.position.set(0,1,0);drill.rotation.x=Math.PI;g.add(drill)}g.userData={id:n.id,type:n.type,heat:n.heat,scale:1};return g}
function syncDeposits(M,s){let key=s.deposits.map(d=>d.type+':'+d.x+':'+d.y+':'+(d.qty>0)).join('|');if(depositGroup.userData.key===key)return;depositGroup.clear();depositGroup.userData.key=key;for(let d of s.deposits){if(d.type==='core'||d.qty<=0)continue;let g=new THREE.Group(),p=positionOf(d,3);let ring=new THREE.Mesh(new THREE.TorusGeometry(d.r*.65,1.4,5,32),mat(d.type==='silicate'?'#d5a558':d.type==='metal'?'#91a8bc':'#c17ade',d.type==='silicate'?'#dfaa57':d.type==='metal'?'#7b9db4':'#b55ddc',.65));ring.rotation.x=-Math.PI/2;g.add(ring);for(let i=0;i<7;i++){let a=i*Math.PI*2/7,cr=new THREE.Mesh(new CrystalGeometry(d.type==='shard'?5:7,d.type==='shard'?18:25+(i%3)*5),d.type==='silicate'?materials.gold:d.type==='metal'?materials.ice:materials.violet);cr.position.set(Math.cos(a)*d.r*.35,10,Math.sin(a)*d.r*.35);cr.rotation.z=.14*Math.sin(i);cr.castShadow=true;g.add(cr)}g.position.copy(p);depositGroup.add(g)}}
function disposeGroup(g){for(const o of [...g.children]){o.traverse?.(x=>{x.geometry?.dispose?.();if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material?.dispose?.()})}g.clear()}function addTube(a,b,color,radius=.9){let curve=new THREE.LineCurve3(a,b),mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,12,radius,5,false),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.9,transparent:true,opacity:.86}));networkGroup.add(mesh)}
function syncNetwork(s,M,t){let live=s.nodes.filter(n=>n.grow<=0),key=live.map(n=>`${n.id}:${n.x}:${n.y}:${n.heat>85?1:0}`).join('|');if(key===networkKey)return;networkKey=key;disposeGroup(networkGroup);for(let n of live){for(let q of [{x:0,y:0,id:0},...live.filter(a=>a!==n)]){if(q.id>n.id&&q.id!==0)continue;if(M.dist(n,q)<M.LINK*(M.has(s,'swarm')?1.25:1)&&M.connected(s,n))addTube(positionOf(n,7),positionOf(q,7),n.heat>85?'#fa6b57':'#56d8d1',n.type==='relay'?1.4:.85)}}}
function syncBuildings(s){let active=new Set(s.nodes.map(n=>n.id));for(let [id,g]of buildMeshes)if(!active.has(id)){buildingGroup.remove(g);buildMeshes.delete(id)}for(let n of s.nodes){let g=buildMeshes.get(n.id);if(!g){g=makeBuilding(n);buildingGroup.add(g);buildMeshes.set(n.id,g)}g.position.copy(positionOf(n,0));let full=n.type==='resonator'?2.5:2.5,progress=n.grow>0?Math.max(.1,1-n.grow/full):1;g.scale.setScalar(progress);g.userData.heat=n.heat;let model=g.children[1];model.material=colorFor(n.type,n.heat);if(n.type==='resonator'&&n.mode==='high')model.material=materials.violet;model.rotation.y=s.t*.35+n.id;if(n.heat>50){let f=1+.035*Math.sin(s.t*8);g.scale.multiplyScalar(f)}}}
function syncDrones(s){let active=new Set(s.drones.map((d,i)=>d.node+'-'+i));for(let [key,g]of droneMeshes)if(!active.has(key)){droneGroup.remove(g);droneMeshes.delete(key)}s.drones.forEach((d,i)=>{let key=d.node+'-'+i,g=droneMeshes.get(key);if(!g){g=new THREE.Group();let body=new THREE.Mesh(new THREE.OctahedronGeometry(4,0),materials.white);body.castShadow=true;g.add(body);let wing=new THREE.Mesh(new THREE.BoxGeometry(13,1,2),materials.gold);g.add(wing);droneGroup.add(g);droneMeshes.set(key,g)}g.position.copy(positionOf(d,15+Math.sin(s.t*7+i)*2))})}
function syncCargo(s){let ids=new Set(s.items.map(i=>i.id));for(let [id,g]of cargoMeshes)if(!ids.has(id)){cargoGroup.remove(g);g.geometry?.dispose?.();cargoMeshes.delete(id)}for(let item of s.items){let g=cargoMeshes.get(item.id);if(!g){let material=item.kind==='silicate'?materials.gold:item.kind==='metal'?materials.ice:item.kind==='shard'||item.kind==='shards'?materials.violet:item.kind==='xeno'?materials.white:materials.teal;let geo=item.phase==='product'?new THREE.OctahedronGeometry(4.8,1):new THREE.DodecahedronGeometry(4.1,0);g=new THREE.Mesh(geo,material);g.castShadow=true;cargoGroup.add(g);cargoMeshes.set(item.id,g)}g.position.copy(positionOf(item,7+Math.sin(s.t*4+item.id)*1.4));g.rotation.set(s.t*.3,item.id,s.t*.25);g.visible=item.phase!=='picked'&&item.phase!=='carried'&&item.phase!=='carriedProduct'}}function syncRoutes(s){let a=routeLine.geometry.attributes.position,idx=0;for(let d of s.drones){let item=s.items.find(i=>i.id===d.cargo),target;if(d.phase==='toOre')target=item||d;else if(d.phase==='toFactory')target=s.nodes.find(n=>n.id===d.target)||d;else if(d.phase==='toCore')target={x:0,y:0};else target=s.nodes.find(n=>n.id===d.node)||d;let p=positionOf(d,9),q=positionOf(target,9);if(idx+6>a.array.length)break;a.array[idx++]=p.x;a.array[idx++]=p.y;a.array[idx++]=p.z;a.array[idx++]=q.x;a.array[idx++]=q.y;a.array[idx++]=q.z}a.needsUpdate=true;routeLine.geometry.setDrawRange(0,idx/3)}function setCamera(v){if(!camera)return;let target=V(v.x||0,heightAt(v.x||0,v.y||0),v.y||0),yaw=(v.rot||0)+.15,pitch=.73,distance=490/(v.zoom||1);camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(target);camera.updateMatrixWorld();lastView={...v}}
function project(p,v){if(!camera)return{x:0,y:0};setCamera(v);let q=positionOf(p,p.z||12).project(camera);return{x:(q.x*.5+.5)*W,y:(-.5*q.y+.5)*H}}
function groundAtPointer(p,v){if(!camera)return{x:0,y:0};setCamera(v);mouse.set(p.x/W*2-1,-p.y/H*2+1);raycaster.setFromCamera(mouse,camera);let hit=raycaster.intersectObject(asteroid,false)[0];if(!hit)return{x:0,y:0};return{x:hit.point.x,y:hit.point.z}}
function draw(s,v,pointer,preview,ok,selected,quality=true){if(!renderer)return;let M=window.SilModel,t=s.t;setCamera(v);syncDeposits(M,s);syncBuildings(s);syncDrones(s);syncCargo(s);syncRoutes(s);syncNetwork(s,M,t);if(particleField)particleField.rotation.y=t*.0008;
let stamp=[s.nodes.filter(n=>n.type==='radiator'&&n.grow<=0).map(n=>n.id).join(','),preview?`${Math.round(preview.x)}:${Math.round(preview.y)}:${ok}:${selected}`:'none'].join('|');if(stamp!==overlayKey){if(window._heatRings){scene.remove(window._heatRings);disposeGroup(window._heatRings)}let overlays=new THREE.Group();for(let n of s.nodes){if(n.type==='radiator'&&n.grow<=0){let ring=new THREE.Mesh(new THREE.TorusGeometry(165,1.0,4,64),new THREE.MeshBasicMaterial({color:'#94b8ff',transparent:true,opacity:.29}));ring.rotation.x=-Math.PI/2;ring.position.copy(positionOf(n,1.7));overlays.add(ring)}}if(preview){let ghost=new THREE.Mesh(new CrystalGeometry(10,28),new THREE.MeshBasicMaterial({color:ok?'#73f2d5':'#ff7168',transparent:true,opacity:.62,wireframe:true}));ghost.position.copy(positionOf(preview,20));overlays.add(ghost);let radius=selected==='radiator'?165:M.LINK;let ring=new THREE.Mesh(new THREE.TorusGeometry(radius,1,4,72),new THREE.MeshBasicMaterial({color:ok?'#5ce1cd':'#f17068',transparent:true,opacity:.14,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.copy(positionOf(preview,1));overlays.add(ring)}scene.add(overlays);window._heatRings=overlays;overlayKey=stamp}
coreGroup.children.forEach((m,i)=>{if(i>0)m.rotation.y+=.003*(i%3+1)});coreGroup.scale.setScalar(s.ritual?1+.06*Math.sin(t*5):1);renderer.render(scene,camera)}
function initDone(){init();window.SilRender={resize,draw,project,unproject:groundAtPointer,get size(){return{W,H}},is3D:!!renderer,setQuality(high){if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio||1,high?1.6:1));resize()}},dispose(){renderer?.dispose()}};window.dispatchEvent(new Event('silicide-render-ready'))}
// A single custom polyhedral-crystal primitive is reused for every structure.
class CrystalGeometry extends THREE.BufferGeometry{constructor(radius=10,height=24){super();let half=height/2,ring=[[-.7,-.45],[-.35,-1],[.45,-.7],[.85,-.15],[.7,.5],[.12,1],[-.6,.65]],verts=[];for(let i=0;i<ring.length;i++){let a=ring[i],b=ring[(i+1)%ring.length];verts.push(0,half,0,a[0]*radius,0,a[1]*radius,b[0]*radius,0,b[1]*radius,a[0]*radius,0,a[1]*radius,0,-half,0,b[0]*radius,0,b[1]*radius)}this.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));this.computeVertexNormals()}};
initDone();})();