// Renderer-independent deterministic smoke tests for the exact game model used by the browser.
global.window=global;require('./model.js');const M=global.SilModel,assert=require('node:assert/strict');let s=M.fresh();
function b(type,x,y){let r=M.build(s,type,{x,y});assert.equal(r.ok,true,`${type} at ${x},${y}: ${r.why}`);return r.node}
function run(state,seconds){let left=seconds;while(left>1e-8&&!state.won){let dt=Math.min(.2,left);M.tick(state,dt);left-=dt}}
// A real zero-energy awakening followed by a reachable, connected starter chain.
assert.equal(s.resources.energy,0);let res=b('resonator',70,0);let relay=b('relay',-90,-40);run(s,3);let ext=b('extractor',-205,-115);let refinery=b('refinery',-55,95);let rad=b('radiator',0,-120);let rad2=b('radiator',-150,0);assert.equal(M.connected(s,ext),true);assert.equal(M.canPlace(s,'extractor',{x:180,y:220}).ok,false);
// Mining creates distinct ore entities. They travel by carrier, wait in a factory queue,
// are transformed after processing time, then physically delivered to the Matriarch.
let before=s.resources.sil;run(s,300);assert(s.resources.energy>0,'resonator should produce energy');assert(s.resources.sil>before,'refinery output should reach the Matriarch');assert(s.stats.delivered>0,'discrete manufactured cargo should be delivered');assert(s.log.some(x=>x.includes('переработал сырьё')),'the refinery must transform raw ore');assert(s.log.some(x=>x.includes('Матка приняла готовый груз')),'finished product must go through physical cargo delivery');assert(s.drones.length>0,'an actual carrier entity must exist');assert(rad.heat<35,'radiator remains cool');assert(res.heat<80,'nearby radiator cools resonator');
// Research is gated by a matured connected lab and technologies have real prerequisites.
s.resources.sil+=200;s.resources.metal+=20;let lab=b('lab',100,75);run(s,3);s.resources.shards=20;s.resources.energy=200;assert.equal(M.research(s,'veins').ok,false);assert.equal(M.research(s,'morph').ok,true);assert.equal(M.has(s,'morph'),true);assert.equal(M.research(s,'veins').ok,true);
// Versioned saves migrate old v2 data safely and never persist a frozen pause.
s.paused=true;let restored=M.deserialize(M.serialize(s));assert(restored&&restored.nodes.length===s.nodes.length);assert.equal(restored.paused,false);assert(Array.isArray(restored.items));let legacy=M.deserialize(JSON.stringify({version:2,state:{...s,drones:[{node:4,phase:'home',carry:5}]}}));assert(legacy&&legacy.drones.length===0,'legacy courier schema must be safely migrated');let legacy3=M.deserialize(JSON.stringify({version:3,state:s}));assert(legacy3,'v3 saves migrate into v5-compatible chapter-I state');let legacy4State=M.fresh();legacy4State.version=4;let legacy4=M.deserialize(JSON.stringify({version:4,state:legacy4State}));assert(legacy4&&legacy4.chapter===1,'v4 saves safely migrate to the current chapter-I schema');let corrupt=JSON.parse(M.serialize(s));corrupt.state.resources.sil='NaN';assert.equal(M.deserialize(JSON.stringify(corrupt)),null,'non-numeric resources are rejected');assert.equal(M.deserialize('{bad json'),null);let depleted=JSON.parse(M.serialize(s));depleted.state.deposits[0].qty=0;let loadedDepleted=M.deserialize(JSON.stringify(depleted));let freshAgain=M.fresh();assert.equal(loadedDepleted.deposits[0].qty,0,'save preserves depleted-ore state');assert.equal(freshAgain.deposits[0].qty,M.DEPOSITS[0].qty,'new game restores independent vein capacity');
// Independent oscillators really produce a simultaneous chord; extractor tuning is local to the selected ore.
let tones=M.fresh(),toneA=M.build(tones,'resonator',{x:70,y:0}).node,toneB=M.build(tones,'resonator',{x:-70,y:0}).node;toneA.grow=toneB.grow=0;assert.equal(M.hasChord(tones),false,'one tone is not an accord');toneB.frequency=1200;toneB.mode='high';assert.equal(M.hasChord(tones),true,'432 and 1200 coexist on separate resonators');tones.freq=700;assert.equal(M.hasChord(tones),true,'the obsolete global tuner cannot erase independently generated tones');assert(M.TECHS.length>=12,'new optional branches exist');
let tuned=M.fresh(),source=M.build(tuned,'resonator',{x:70,y:0}).node;M.build(tuned,'relay',{x:-90,y:-40});run(tuned,3);let miner=M.build(tuned,'extractor',{x:-205,y:-115}).node;assert.equal(miner.frequency,432,'extractor auto-selects the nearby silicate frequency');let ore=tuned.deposits.find(d=>d.type==='silicate');miner.frequency=576;let stock=ore.qty;run(tuned,20);assert.equal(ore.qty,stock,'wrong extractor frequency stops fragmentation');miner.frequency=432;run(tuned,15);assert(ore.qty<stock,'correct local frequency fragments ore');assert(tuned.items.some(i=>i.kind==='silicate'),'mining outputs physical ore cargo');
let mod=M.fresh(),pulseNode=M.build(mod,'resonator',{x:70,y:0}).node;mod.tech.push('modular','pulse');mod.resources.sil=100;mod.resources.metal=20;assert(M.upgradeNode(mod,pulseNode.id,'pulse').ok,'impulse coil can be attached as a real building path');run(mod,10);assert(pulseNode.specialization==='pulse'&&pulseNode.charge<8,'pulse path accumulates and releases charge');let burst=M.fresh();burst.tech.push('modular','pulse');let gen=M.build(burst,'resonator',{x:70,y:0}).node;M.build(burst,'relay',{x:-90,y:-40});run(burst,3);let burstMine=M.build(burst,'extractor',{x:-205,y:-115}).node;gen.grow=burstMine.grow=0;assert(M.upgradeNode(burst,gen.id,'pulse').ok);assert(M.upgradeNode(burst,burstMine.id,'impulse').ok);run(burst,5);assert(burst.items.some(i=>i.kind==='silicate'&&i.amount===20),'matched pulse releases a ×4 discrete ore batch');
// Finale is reachable with infrastructure, energy reserve, cooling, 2 resonances and the chord.
let end=M.fresh();end.tech=M.TECHS.map(t=>t.id);end.resources={sil:999,metal:999,energy:220,shards:90,xeno:1};end.nodes=[{id:1,type:'resonator',x:-35,y:0,grow:0,heat:15,mode:'base',work:0},{id:2,type:'resonator',x:35,y:0,grow:0,heat:15,mode:'high',work:0},{id:3,type:'radiator',x:0,y:45,grow:0,heat:10,work:0},{id:4,type:'chamber',x:0,y:-60,grow:0,heat:10,work:0}];end.nextId=5;end.freq=1200;assert.equal(M.startRitual(end).ok,true);run(end,70);assert.equal(end.won,true,'prepared ritual must reach the actual chapter ending');
console.log('PASS: zero-energy start · real-time growth · network · discrete mining cargo → refinery conversion → Matriarch delivery · energy/heat · research · versioned save · achievable chapter finale');