// Renderer-independent deterministic smoke tests for the exact game model used by the browser.
global.window=global;require('./model.js');const M=global.SilModel,assert=require('node:assert/strict');let s=M.fresh();
function b(type,x,y){let r=M.build(s,type,{x,y});assert.equal(r.ok,true,`${type} at ${x},${y}: ${r.why}`);return r.node}
function run(state,seconds){let left=seconds;while(left>1e-8&&!state.won){let dt=Math.min(.2,left);M.tick(state,dt);left-=dt}}
// A real zero-energy awakening followed by a reachable, connected starter chain.
assert.equal(s.resources.energy,0);let res=b('resonator',70,0);let relay=b('relay',-90,-40);run(s,3);let ext=b('extractor',-205,-115);let refinery=b('refinery',-55,95);let rad=b('radiator',0,-120);let rad2=b('radiator',-150,0);assert.equal(M.connected(s,ext),true);assert.equal(M.canPlace(s,'extractor',{x:180,y:220}).ok,false);
// Mining creates distinct ore entities. They travel by carrier, wait in a factory queue,
// are transformed after processing time, then physically delivered to the Matriarch.
let before=s.resources.sil;run(s,300);assert(s.resources.energy>0,'resonator should produce energy');assert(s.resources.sil>before,'refinery output should reach the Matriarch');assert(s.stats.delivered>0,'discrete manufactured cargo should be delivered');assert(s.log.some(x=>x.includes('переработал сырьё')),'the refinery must transform raw ore');assert(s.log.some(x=>x.includes('Матка приняла готовый груз')),'finished product must go through physical cargo delivery');assert(s.drones.length>0,'an actual carrier entity must exist');assert(rad.heat<35,'radiator remains cool');assert(res.heat<80,'nearby radiator cools resonator');
// Research is gated by a matured connected lab and technologies have real prerequisites.
s.resources.sil+=200;s.resources.metal+=20;let lab=b('lab',100,75);run(s,3);s.resources.shards=20;s.resources.energy=200;assert.equal(M.research(s,'veins').ok,false);assert.equal(M.research(s,'morph').ok,true);assert.equal(M.has(s,'morph'),true);assert.equal(M.research(s,'veins').ok,true);
// Versioned saves migrate old v2 data safely and never persist a frozen pause.
s.paused=true;let restored=M.deserialize(M.serialize(s));assert(restored&&restored.nodes.length===s.nodes.length);assert.equal(restored.paused,false);assert(Array.isArray(restored.items));let legacy=M.deserialize(JSON.stringify({version:2,state:{...s,drones:[{node:4,phase:'home',carry:5}]}}));assert(legacy&&legacy.drones.length===0,'legacy courier schema must be safely migrated');assert.equal(M.deserialize('{bad json'),null);let depleted=JSON.parse(M.serialize(s));depleted.state.deposits[0].qty=0;let loadedDepleted=M.deserialize(JSON.stringify(depleted));let freshAgain=M.fresh();assert.equal(loadedDepleted.deposits[0].qty,0,'save preserves depleted-ore state');assert.equal(freshAgain.deposits[0].qty,M.DEPOSITS[0].qty,'new game restores independent vein capacity');
// Finale is reachable with infrastructure, energy reserve, cooling, 2 resonances and the chord.
let end=M.fresh();end.tech=M.TECHS.map(t=>t.id);end.resources={sil:999,metal:999,energy:220,shards:90,xeno:1};end.nodes=[{id:1,type:'resonator',x:-35,y:0,grow:0,heat:15,mode:'base',work:0},{id:2,type:'resonator',x:35,y:0,grow:0,heat:15,mode:'high',work:0},{id:3,type:'radiator',x:0,y:45,grow:0,heat:10,work:0},{id:4,type:'chamber',x:0,y:-60,grow:0,heat:10,work:0}];end.nextId=5;end.freq=1200;assert.equal(M.startRitual(end).ok,true);run(end,70);assert.equal(end.won,true,'prepared ritual must reach the actual chapter ending');
console.log('PASS: zero-energy start · real-time growth · network · discrete mining cargo → refinery conversion → Matriarch delivery · energy/heat · research · versioned save · achievable chapter finale');