'use strict';
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const assert = require('node:assert/strict');
const base='http://127.0.0.1:8123';
async function server(){let p=spawn('python3',['-m','http.server','8123','--bind','127.0.0.1'],{cwd:process.cwd(),stdio:'ignore'});for(let i=0;i<80;i++){try{let r=await fetch(base);if(r.ok)return p}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('local static server did not start')}
(async()=>{let srv, browser;try{srv=await server();browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let page=await browser.newPage({viewport:{width:1360,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text())});await page.goto(base+'/?dev=1',{waitUntil:'load'});await page.waitForFunction(()=>window.SilGame&&window.SilRender?.is3D,{timeout:15000});await page.waitForTimeout(1000);
assert.equal(await page.evaluate(()=>SilRender.is3D),true,'real WebGL 3D renderer should initialize');let rotBefore=await page.evaluate(()=>SilGame.camera().rot);await page.keyboard.press('q');assert.notEqual(await page.evaluate(()=>SilGame.camera().rot),rotBefore,'Q/E rotates the true 3D camera');await page.locator('#world').hover();await page.mouse.wheel(0,-160);assert(await page.evaluate(()=>SilGame.camera().zoom)>1,'mouse wheel changes camera distance');let before=await page.evaluate(()=>SilGame.state().t);await page.waitForTimeout(5000);let after=await page.evaluate(()=>SilGame.state().t);assert(after-before>=3.5,`simulation should run beyond the former ~4s freeze (advanced ${(after-before).toFixed(2)}s)`);
// UI construction selection and Esc cancellation are browser-level inputs.
await page.locator('.buildcard').filter({hasText:'Резонатор'}).click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>SilGame.state().nodes.length),0,'Esc must cancel without spending');
// Place the first resonator by the same canvas ray-pick handler used by players.
await page.locator('.buildcard').filter({hasText:'Резонатор'}).click();let coords=await page.evaluate(()=>{let r=document.querySelector('#world').getBoundingClientRect(),p=SilRender.project({x:70,y:0},{x:0,y:0,zoom:1,rot:0});return{x:r.x+p.x,y:r.y+p.y}});await page.mouse.click(coords.x,coords.y);assert.equal(await page.evaluate(()=>SilGame.state().nodes[0]?.type),'resonator','world click grows actual resonator');await page.evaluate(()=>SilGame.simulate(4));let rs=await page.evaluate(()=>({growth:SilGame.state().nodes[0].grow,energy:SilGame.state().resources.energy}));assert.equal(rs.growth,0,'construction timer completes');assert(rs.energy>0,'zero-energy starter produces energy after growth');
// Connected factory and quarry: verify actual cargo entities, conversion and delivery.
let builds=[['refinery',-55,95],['relay',-90,-40],['radiator',0,-120],['radiator',-150,0]];for(let [t,x,y]of builds){let r=await page.evaluate(([t,x,y])=>SilGame.build(t,x,y),[t,x,y]);assert.equal(r.ok,true,`${t} placement: ${r.why}`)}await page.evaluate(()=>SilGame.simulate(4));let mine=await page.evaluate(()=>SilGame.build('extractor',-205,-115));assert.equal(mine.ok,true,`extractor placement: ${mine.why}`);assert(await page.evaluate(()=>SilModel.connected(SilGame.state(),SilGame.state().nodes.find(n=>n.type==='extractor'))),'extractor must join the live network');let stock0=await page.evaluate(()=>SilGame.state().resources.sil);await page.evaluate(()=>SilGame.simulate(260));let production=await page.evaluate(()=>({sil:SilGame.state().resources.sil,delivered:SilGame.state().stats.delivered,items:SilGame.state().items.length,drone:SilGame.state().drones.length,logs:SilGame.state().log.slice(0,40)}));assert(production.sil>stock0,'processed outputs reach Matriarch inventory');assert(production.delivered>0,'carrier transports concrete goods');assert(production.drone>0,'carrier is an entity, not a label');assert(production.logs.some(x=>x.includes('переработал сырьё')),'factory transforms raw resources');
// Save/load, pause, diagnostics and monotonic frame catch-up.
await page.locator('#saveBtn').click();assert(await page.evaluate(()=>!!localStorage.getItem('silicide-save-v3')),'manual save');await page.locator('#pauseBtn').click();let frozen=await page.evaluate(()=>SilGame.state().t);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>SilGame.state().t),frozen,'pause freezes deterministic game time');await page.locator('#pauseBtn').click();await page.waitForTimeout(500);assert(await page.evaluate(()=>SilGame.state().t)>frozen,'resume continues');let catchup=await page.evaluate(()=>{let s=SilGame.state().t;SilGame.advanceWall(3);return SilGame.state().t-s});assert(catchup>2.9,'3-second delayed frame catch-up must not be discarded');let logs=await page.evaluate(()=>SilLog.get());assert(logs.some(x=>x.event==='sim.frame.gap'||x.event==='sim.snapshot'),'runtime journal contains health snapshots');await page.locator('.tab[data-tab="log"]').click();await page.waitForTimeout(900);assert((await page.locator('#log').innerText()).includes('sim.snapshot'),'live diagnostic events appear in the Signals tab');let downloadPromise=page.waitForEvent('download');await page.locator('#exportLog').click();let download=await downloadPromise;assert(download.suggestedFilename().endsWith('.json'),'journal exports as JSON');assert.deepEqual(errors,[],'no browser runtime errors: '+errors.join('\n'));
console.log(`PASS browser: WebGL 3D; live clock advanced ${(after-before).toFixed(1)} s after the old freeze point; canvas placement/cancel; energy; refinery cargo; cooling; save/pause/resume; slow-frame catch-up; ${logs.length} diagnostic entries`);
}catch(e){console.error('BROWSER TEST FAILED:',e.stack||e);process.exitCode=1}finally{await browser?.close();srv?.kill('SIGTERM')}})();
