'use strict';
// End-to-end campaign simulation. It calls the same model methods (`build`, `research`, `tick`,
// `startRitual`) used by the UI, advances with the same fixed 0.2 game-second step, and never
// grants resources/tech. Only meteor impact randomness is seeded to make the CI run repeatable.
global.window=global;global.SilLog={push(){}};const M=require('../model.js')&&global.SilModel,assert=require('node:assert/strict');Math.random=()=>.999;let s=M.fresh(),elapsed=0,actions=[];
function advance(seconds){let left=seconds;while(left>1e-8&&!s.won){let dt=Math.min(.2,left);M.tick(s,dt);left-=dt;elapsed+=dt}}
function waitFor(fn,what,limit=3600){let start=elapsed;while(!fn()&&elapsed-start<limit&&!s.won)advance(.2);assert(fn(),`timeout waiting for ${what}; t=${elapsed.toFixed(1)}, resources=${JSON.stringify(s.resources)}, phase=${M.getPhase(s)[0]}, nodes=${JSON.stringify(s.nodes.map(n=>({type:n.type,grow:n.grow.toFixed(1),heat:n.heat.toFixed(0),work:n.work.toFixed(1),link:M.connected(s,n)})))}, drones=${JSON.stringify(s.drones)}, items=${JSON.stringify(s.items.slice(-12))}, shardVeins=${s.deposits.filter(d=>d.type==='shard').map(d=>d.qty)}`)}
function place(type,x,y){let start=elapsed;for(let k=0;k<4000;k++){let result=M.build(s,type,{x,y});if(result.ok){actions.push(`build ${type} @ ${x},${y} t=${elapsed.toFixed(1)}`);advance(3);return result.node}if(!result.why.includes('Недостаточно ресурсов')){if(result.why.includes('Не подключено')){advance(1);continue}throw Error(`cannot place ${type} @ ${x},${y}: ${result.why}`)}advance(5)}throw Error(`build timeout ${type} after ${(elapsed-start).toFixed(0)}s; ${JSON.stringify(s.resources)}`)}
function research(id){let start=elapsed;waitFor(()=>s.resources.shards>=M.TECHS.find(t=>t.id===id).cost&&s.resources.energy>=M.TECHS.find(t=>t.id===id).energy,`research resources ${id}`,2400);let result=M.research(s,id);assert(result.ok,`research ${id}: ${result.why}`);actions.push(`research ${id} t=${elapsed.toFixed(1)}`);}
// Wake + first power; physically mine, transport and refine. Keep hot machinery in rad range.
place('resonator',70,0);let mainRes=s.nodes.at(-1);place('refinery',-55,95);place('relay',-90,-40);place('radiator',0,-120);place('radiator',-150,0);place('extractor',-205,-115);waitFor(()=>s.stats.delivered>0,'first physical product shipment reaches Matriarch',900);assert(s.log.some(x=>x.includes('Груз создан: silicate')),'raw resources existed as discrete cargo before factory transformation');assert(s.stats.delivered>0,'physical product cargo reached the Matriarch');
// Extend to metal, build the memory lab and shard mine through a real live route.
place('relay',50,-145);place('extractor',30,-270);place('lab',120,75);place('relay',-200,0);place('radiator',-260,-50);place('extractor',-340,4);place('radiator',100,140);
// Replay investments from the actual earned shard inventory; the lab must process ore shipments.
research('morph');research('veins');research('thermal');research('harmonics');research('accord');research('autonomy');
place('nest',120,-145);research('swarm');research('memory');research('xeno');
// Upgrade the network: distinct high-frequency resonator, ward, storage, physical X crystal,
// then the Chamber. Costs are paid from delivered factory outputs only.
place('resonator',170,20);let highRes=s.nodes.at(-1);highRes.mode='high';place('radiator',130,-35);place('ward',80,-90);place('battery',80,105);place('crystallizer',180,-70);
waitFor(()=>s.resources.xeno>=1,'physical Ksenokvartz reaches the Matriarch',1800);place('chamber',250,-85);waitFor(()=>s.resources.energy>=160,'ritual reserve',900);s.freq=1200;highRes.mode='high';mainRes.mode='base';let start=M.startRitual(s);assert(start.ok,`ritual start: ${start.why}`);
let ritualStart=elapsed;waitFor(()=>s.won,'Body II chapter completion',900);assert(s.won&&s.ritualProgress>=1,'first chapter reaches its real victory state');assert(elapsed-ritualStart<=300,'ritual trial resolves in a reasonable timeframe');assert(s.stats.delivered>100,'campaign materially moved resources by courier');assert(s.stats.researched===9,'all nine real technology effects researched');
console.log(`PASS FULL CHAPTER: ${elapsed.toFixed(1)} simulated seconds; ${actions.length} construction/research actions; ${s.stats.delivered.toFixed(0)} delivered material units; ${s.stats.researched} technologies; Body II finale`);
// Continue from the genuine chapter-I victory state above; no chapter-II stock or tech is granted.
let c2Elapsed=0;const w2=()=>s.world2;
function c2Advance(seconds){let left=seconds;while(left>1e-8&&!s.won){let dt=Math.min(.2,left);M.tick(s,dt);left-=dt;c2Elapsed+=dt}}
function c2Wait(fn,what,limit=1200){let start=c2Elapsed;while(!fn()&&c2Elapsed-start<limit)c2Advance(.2);assert(fn(),`chapter II timeout waiting ${what}; t=${s.t.toFixed(1)}, resources=${JSON.stringify(s.resources)}, stock=${JSON.stringify(w2().stocks)}, phase=${M.getPhase(s)[0]}`)}
function c2Research(id){let t=M.TECHS.find(q=>q.id===id);assert(t,`missing tech ${id}`);c2Wait(()=>s.resources.shards>=t.cost&&s.resources.energy>=t.energy,`research inputs ${id}`);let r=M.research(s,id);assert(r.ok,`research ${id}: ${r.why}`)}
function c2Build(type,asteroidId,i,j){w2().activeAsteroid=asteroidId;let r=M.build(s,type,{asteroidId,i,j});assert(r.ok,`build ${type} at ${asteroidId}:${i},${j}: ${r.why}`);return r.node}
function c2OpenRoute(a,b){let r=M.connectRoute(s,a,b);assert(r.ok,`route ${a}-${b}: ${r.why}`);return r.route}
function c2Send(source,kind,amount){let r=M.sendShipment(s,source,'home',kind,amount);return r}
function c2EnsureHome(kind,target,source,reserve=0){let guard=0;while((s.resources[kind]||0)<target&&guard++<80){let want=Math.min(20,target-(s.resources[kind]||0));c2Wait(()=>M.c2Resource(s,source,kind)>=want+reserve,`${source} ${kind} for home target ${target}`,1500);let r=c2Send(source,kind,want);if(!r.ok){c2Advance(.2);continue}let q=r.shipment;c2Wait(()=>q.phase==='arrived',`shipment ${q.id} delivery`,120)}assert((s.resources[kind]||0)>=target,`home ${kind} reached ${s.resources[kind]} < ${target}`)}
let transition=M.startChapter2(s);assert(transition.ok,`chapter-II transition: ${transition.why}`);assert(s.chapter===2&&s.chapter1Archive?.won,'chapter-I snapshot must be preserved inside the new save');
for(let id of ['c2_survey','c2_seed','c2_gravity','c2_ports','c2_drill'])c2Research(id);
for(let id of ['silica','iron','memory','hollow','hazard','gravity']){c2Wait(()=>s.resources.energy>=4,`scan energy for ${id}`);let r=M.scanAsteroid(s,id);assert(r.ok,`survey ${id}: ${r.why}`)}assert.equal(w2().surveyed.length,7,'all seven bodies surveyed through scanner and energy cost');
// First colony and a real finite silicate deposit. Cargo queues behind a live capacity-one route.
c2Build('seed','silica',0,0);c2Wait(()=>w2().colonies.includes('silica'),'silicate seed landing');c2Build('extractor','silica',-1,0);let silicaRoute=c2OpenRoute('home','silica');c2Wait(()=>M.c2Resource(s,'silica','sil')>=82,'two real silicate shipments plus remote resonator reserve',180);
let q1=c2Send('silica','sil',20);assert(q1.ok);let q2=c2Send('silica','sil',20);assert(q2.ok&&q2.shipment.phase==='queued','route must maintain a real freight queue');silicaRoute.blockedUntil=s.t+2;c2Advance(.2);assert(q1.shipment.blocked,'in-flight freight must stop at a broken route');let held=q1.shipment.remaining;c2Advance(.8);assert.equal(q1.shipment.remaining,held,'blocked cargo keeps its ETA and is not teleported');assert(M.repairRoute(s,silicaRoute.id).ok,'route repair is a real action');c2Wait(()=>q1.shipment.phase==='arrived'&&q2.shipment.phase==='arrived','queued freight recovery',30);assert.equal(s.resources.sil,92,'only arrived silicon enters Matriarch inventory');
// A second colony unlocks real local metal production; no material is conjured on arrival.
c2EnsureHome('sil',48,'silica',42);c2Build('seed','iron',0,0);c2Wait(()=>w2().colonies.includes('iron'),'iron seed landing');c2Build('deepExtractor','iron',1,0);let ironRoute=c2OpenRoute('home','iron');c2EnsureHome('metal',22,'iron');
// Seed memory, then import shards in timed batches to pay for the remaining technology tree.
c2EnsureHome('metal',14,'iron');c2EnsureHome('sil',48,'silica',42);c2Build('seed','memory',0,0);c2Wait(()=>w2().colonies.includes('memory'),'memory seed landing');c2Build('extractor','memory',0,-1);c2OpenRoute('home','memory');
// Remote 1200 Hz oscillator is built from a colony's own mined supply, not the home stash.
c2Wait(()=>M.c2Resource(s,'silica','sil')>=42&&M.c2Resource(s,'silica','metal')>=5,'local materials for remote resonator',1200);w2().activeAsteroid='silica';let high=M.build(s,'resonator',{asteroidId:'silica',i:1,j:0});assert(high.ok,`remote resonator: ${high.why}`);high.node.frequency=1200;c2Wait(()=>high.node.grow<=0,'remote resonance growth');
// A genuine hostile-front interruption: warning, blocked shipment, manual repair, then arrival.
w2().frontNext=s.t+4;let threatCargo=c2Send('silica','sil',2);assert(threatCargo.ok);c2Advance(4.4);assert(w2().frontCount>0&&s.log.some(x=>x.includes('ПРЕДУПРЕЖДЕНИЕ: диссонансный фронт')),'front is warned before impact');let routeBroken=w2().routes.find(r=>r.id===threatCargo.shipment.routeIds[0]);assert(s.t<routeBroken.blockedUntil,'front blocks the route temporarily');assert(threatCargo.shipment.blocked,'freight pauses during the front');M.repairRoute(s,routeBroken.id);c2Wait(()=>threatCargo.shipment.phase==='arrived','post-front freight recovery',30);
// Complete research using only shards produced on the memory body.
for(let [id,cost] of [['c2_distant',5],['c2_phase',10],['c2_memory',16],['c2_multicore',23]]){c2EnsureHome('shards',cost,'memory');c2Research(id)}
assert(M.hasDistributedChord(s),'432/1200 chord must span two separately powered asteroid networks joined by a live route');
// Silicon shipments retain local stock for the planned 1200 Hz resonator until it is built.
// Remaining colonies: funded seeds, finite echorock, and tidal-gravity deposit.
c2EnsureHome('metal',14,'iron');c2EnsureHome('sil',48,'silica',42);c2Build('seed','hazard',0,0);c2Wait(()=>w2().colonies.includes('hazard'),'hazard seed landing');c2Build('deepExtractor','hazard',1,0);c2OpenRoute('home','hazard');
c2EnsureHome('metal',14,'iron');c2EnsureHome('sil',48,'silica',42);c2Build('seed','gravity',0,0);c2Wait(()=>w2().colonies.includes('gravity'),'gravity seed landing');c2Build('extractor','gravity',-1,0);c2OpenRoute('home','gravity');
// Complete home factory materials; the assembler consumes stocks and produces physical component objects.
c2EnsureHome('metal',65,'iron');c2EnsureHome('sil',146,'silica');c2EnsureHome('shards',35,'memory');c2EnsureHome('grav',4,'gravity');c2EnsureHome('echo',2,'hazard');
assert(M.hasDistributedChord(s));w2().activeAsteroid='home';let assembler=c2Build('assembler','home',1,1);c2Wait(()=>assembler.grow<=0,'assembler growth');let asc=c2Build('ascension','home',1,-2);c2Wait(()=>asc.grow<=0,'ascension chamber growth');
c2Wait(()=>s.resources.parts>=2,'two physically assembled and conveyed core parts',180);assert(w2().components.filter(x=>x.phase==='delivered').length>=2,'component production remains discrete and timed');assert(s.world2.harvested>0,'finite local veins were physically mined');assert(w2().asteroids.find(a=>a.id==='silica').deposits[0].qty<360,'visible silica vein physically depleted');
let finale=M.startAscension(s);assert(finale.ok,`Matriarch-II ritual prerequisites: ${finale.why}`);let c2RitualStart=c2Elapsed;c2Wait(()=>s.won,'Matriarch II finale',300);assert(w2().complete&&s.ritualProgress===1,'the ordinary simulation tick completes the chapter-II finale');assert(c2Elapsed-c2RitualStart<=90,'finale resolves in a reasonable timeframe');
let save=M.serialize(s),restored=M.deserialize(save);assert(restored&&restored.chapter===2&&restored.world2.complete,'save/load preserves chapter-II ending and multi-body state');assert(restored.chapter1Archive?.won,'saved chapter-II campaign retains chapter-I archive');assert.equal(M.TECHS.filter(t=>t.chapter===2).length,12,'the chapter-II tech tree contains twelve real-effect technologies');// Isolated deterministic effect checks for the three optional economy upgrades and two resonance defenses.
function c2Probe(){let q=M.deserialize(save);q.won=false;q.world2.complete=false;q.paused=false;for(let r of q.world2.routes){r.disabled=false;r.blockedUntil=0}q.world2.shipments=[];return q}
let dispatch=c2Probe();dispatch.tech=dispatch.tech.filter(id=>id!=='c2_dispatch');dispatch.resources.shards=50;dispatch.resources.energy=200;dispatch.world2.stocks.silica.sil=80;let dispatchResearch=M.research(dispatch,'c2_dispatch');assert(dispatchResearch.ok&&dispatch.world2.routes.every(r=>r.capacity===48),'dispatch research upgrades already-built route capacity');let dispatchBatch=M.sendShipment(dispatch,'silica','home','sil',48);assert(dispatchBatch.ok&&dispatchBatch.shipment.amount===48,'dispatch capacity increases the actual paid shipment size');
let remoteBase=c2Probe();remoteBase.tech=remoteBase.tech.filter(id=>id!=='c2_remote');let remoteMiner=remoteBase.nodes.find(n=>n.type==='extractor'&&n.asteroidId==='silica');remoteBase.world2.asteroids.find(a=>a.id==='silica').deposits[0].qty=360;remoteBase.world2.stocks.silica.sil=0;remoteMiner.grow=0;remoteMiner.heat=6;remoteMiner.work=9.9;remoteBase.world2.frontNext=remoteBase.t+200;M.tick(remoteBase,.2);let baseYield=remoteBase.world2.stocks.silica.sil,baseDepletion=360-remoteBase.world2.asteroids.find(a=>a.id==='silica').deposits[0].qty;let remoteUpgrade=c2Probe();remoteUpgrade.tech=remoteUpgrade.tech.filter(id=>id!=='c2_remote');remoteUpgrade.tech.push('c2_remote');let remoteNode=remoteUpgrade.nodes.find(n=>n.type==='extractor'&&n.asteroidId==='silica');remoteUpgrade.world2.asteroids.find(a=>a.id==='silica').deposits[0].qty=360;remoteUpgrade.world2.stocks.silica.sil=0;remoteNode.grow=0;remoteNode.heat=6;remoteNode.work=9.9;remoteUpgrade.world2.frontNext=remoteUpgrade.t+200;M.tick(remoteUpgrade,.2);assert.equal(remoteUpgrade.world2.stocks.silica.sil,Math.floor(baseYield*1.25),'autonomous-colony research raises actual remote yield');assert.equal(360-remoteUpgrade.world2.asteroids.find(a=>a.id==='silica').deposits[0].qty,baseDepletion,'remote yield does not accelerate depletion');
let selectiveBase=c2Probe();selectiveBase.tech=selectiveBase.tech.filter(id=>id!=='c2_selective');let echorock=selectiveBase.world2.asteroids.find(a=>a.id==='hazard').deposits[0];echorock.qty=48;selectiveBase.world2.stocks.hazard.echo=0;let deep=selectiveBase.nodes.find(n=>n.type==='deepExtractor'&&n.asteroidId==='hazard');deep.grow=0;deep.heat=6;deep.work=14.9;selectiveBase.world2.frontNext=selectiveBase.t+200;M.tick(selectiveBase,.2);let basicEcho=selectiveBase.world2.stocks.hazard.echo;let selective=c2Probe();selective.tech.push('c2_selective');let echo2=selective.world2.asteroids.find(a=>a.id==='hazard').deposits[0];echo2.qty=48;selective.world2.stocks.hazard.echo=0;let deep2=selective.nodes.find(n=>n.type==='deepExtractor'&&n.asteroidId==='hazard');deep2.grow=0;deep2.heat=6;deep2.work=14.9;selective.world2.frontNext=selective.t+200;M.tick(selective,.2);assert.equal(selective.world2.stocks.hazard.echo,basicEcho+1,'selective take improves echo yield by one while retaining the same finite vein depletion');assert.equal(echo2.qty,echorock.qty,'selective take preserves four units of vein per cycle');
let phaseProbe=c2Probe();phaseProbe.world2.frontWarning=false;phaseProbe.world2.frontNext=phaseProbe.t+.1;M.tick(phaseProbe,.2);assert(phaseProbe.world2.routes.every(r=>r.blockedUntil===0),'phase bridge prevents a front from blocking routes');let memoryOn=c2Probe(),memoryOff=c2Probe();memoryOff.tech=memoryOff.tech.filter(id=>id!=='c2_memory');for(let q of [memoryOn,memoryOff]){q.world2.ritual={progress:0,stress:0,elapsed:0};let hot=q.nodes.find(n=>n.type==='resonator');hot.heat=100;q.world2.frontNext=q.t+200;M.tick(q,.2)}assert(memoryOn.world2.ritual.stress<memoryOff.world2.ritual.stress,'harmonic memory reduces measured ritual stress');
console.log(`PASS FULL CHAPTER II: ${c2Elapsed.toFixed(1)} simulated seconds; ${w2().asteroids.length} separate asteroids; ${w2().delivered} delivered resources; ${w2().routes.length} routes; queued/repairable freight; finite veins; 12 technology effects exercised; ${s.stats.researched} chapter-II researches; Matriarch II finale`);

